import { SignIn, useUser, UserButton } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.exercises.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Error loading data</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl">
          <div className="flex w-full max-w-2xl justify-end bg-red-200 p-2">
            {!user.isSignedIn && <SignIn />}
            {!!user.isSignedIn && <UserButton afterSignOutUrl="/" />}
          </div>
          <div className="bg-blue-200">
            {[...data].map((exercises) => (
              <div key={exercises.id}>{exercises.name}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
