import { SignIn, useUser, UserButton } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePlanWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div>{user.firstName ?? user.emailAddresses[0]?.emailAddress ?? ""}</div>
  );
};

export default function Home() {
  const user = useUser();

  const { data: exData, isLoading: exIsLoading } =
    api.exercises.getAll.useQuery();

  const { data: mesoData, isLoading: mesoIsLoading } =
    api.mesocycles.getAll.useQuery();

  const { data: workoutData, isLoading: workoutIsLoading } =
    api.workouts.getAll.useQuery();

  if (exIsLoading || mesoIsLoading || workoutIsLoading) {
    return <div>Loading...</div>;
  }

  if (!exData || !mesoData || !workoutData) {
    return <div>Error loading data</div>;
  }

  return (
    <>
      <Head>
        <title>gAIns - AI Training App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl">
          <div className="flex w-full max-w-2xl justify-end bg-red-200 p-2">
            {!user.isSignedIn && <SignIn />}
            {!!user.isSignedIn && <UserButton afterSignOutUrl="/" />}
          </div>

          <CreatePlanWizard />

          <div className="bg-blue-400 text-center">
            {[...mesoData].map(({ meso, owner }) => (
              <div key={meso.id}>
                {meso.name} {owner?.id}
              </div>
            ))}
          </div>

          <div className="grid grid-flow-col bg-blue-500 text-center">
            {[...workoutData].map((workouts) => (
              <div key={workouts.id}>{workouts.name}</div>
            ))}
          </div>

          <div className="bg-blue-300">
            {[...exData].map((exercises) => (
              <div key={exercises.id}>{exercises.name}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
